{{- if .Values.deploy -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None
  ports:
  {{- include "boots.ports" ( merge .Values ( dict "PortKey" "port" ) ) | indent 2 }}
  selector:
    app: {{ .Values.name }}
{{- end -}}
