{{- if and .Values.stack.enabled .Values.stack.relay.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stack.name}}-relay
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.stack.name }}-relay
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.stack.name }}-relay
    spec:
      containers:
      - name: {{ .Values.stack.name }}-relay
        image: {{ .Values.stack.relay.image }}
        args: ["-id", "{{ .Values.stack.relay.sourceInterface }}", "-iu", "cni0", "boots.tink-system.svc.cluster.local"]
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
{{- end -}}